// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThePopupFrame: typeof import('./src/components/ThePopupFrame.vue')['default']
    ThePopupMessage: typeof import('./src/components/ThePopupMessage.vue')['default']
    ThePopupMiddle: typeof import('./src/components/ThePopupMiddle.vue')['default']
    ThePopupUp: typeof import('./src/components/ThePopupUp.vue')['default']
    ThePopupUpMiddle: typeof import('./src/components/ThePopupUpMiddle.vue')['default']
  }
}
